### ISSUE TITLE
Mobile App Initialization

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#53]
# ℹ️ Description
- The aim of this issue is to set up the required environment and run a basic React Native application.

# 🎯 Tasks
- Install the necessary applications (JDK,Android Studio, etc.)
- Set environment variables properly (explained in the instructions at the site given below)
- Run a basic application using React Native

- [x] Nazlıcan Aka
- [x] Yusuf Kağan Çiçekdağ
- [x] Gülşen Sabak
- [x]  Yasin ATLI

You can follow the instructions on [this site](https://reactnative.dev/docs/environment-setup)

**Comment by Pqrq** [comment]
# Some Other Tips (from my case)
- If you have downloaded JDK 17, changing the Gradle version is not required 
- "npm uninstall -g react-native-cli @react-native-community/cli" at the start of "Creating a new application" title is required
- When you successfully initialize, you can continue the rest inside Android Studio IDE (and inside its terminals). It has a README file giving the "rest of the instructions" in order to run a basic application successfully.
- When running the app at the end, make sure that your emulator (opened at the right of your screen I guess) is open :)

Good luck :)

**Comment by Pqrq** [comment]
# About the "Expo" part

* For the Expo part (which I have learned that it is allowed, after initializing my first React Native app, lol), if you have successfully initialized your first React Native app by using the steps explained in [this site](https://reactnative.dev/docs/environment-setup), you do not need to do any extra stuff. Just go to your desired directory, and running the command 
* $ npx create-expo-app
* would suffice for an mobile app initialization. It will ask you a name for your application, and after you fill in the name, it will initialize a basic mobile application for you. 
* Running is similar, just open Android Studio, go to the app's directory (in yur terminal) and run the command
* $ npm run android
* and your app will be run on your emulator. (assuming you've already started your emulator just after opening up Android Studio :) )

**Comment by gulsensabak** [comment]
I have made all initializations. That was a little bit hard for me because of the inefficient storage capacity. but I have handled it.  Thank you  @Pqrq.

**Comment by Pqrq** [comment]
You're welcome @gulsensabak 

@karatashsyn @NazlicanAka have you done the initializations? If you have other tasks instead of mobile, I can remove you from the assignees as it currently seems as "you have this task which has not been completed yet"

Please answer asap :) , as we have our demo tomorrow

**Comment by karatashsyn** [comment]
@Pqrq I have done the tasks related to the web application. You can remove me from the assignees

**Comment by Pqrq** [comment]
@karatashsyn Okay, I am removing you from the assignees and edit the issue accordingly.

**Comment by NazlicanAka** [comment]
@Pqrq I have done the tasks related to the web application. You can remove me from the assignees

**Comment by gulsensabak** [comment]
Since everything is done, I am closing this issue.
