### ISSUE TITLE
Edit Issues

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#54]
# ℹ️ Description
* Every team should edit the issues, their descriptions and labels, properly.

# 🎯 Tasks

- [x] Backend Design
- [x] Web App Development
- [x] Database Design
- [x] Mobile Development

**Comment by karatashsyn** [comment]
[Issue related to web app](https://github.com/bounswe/bounswe2024group10/issues/52) is edited.

**Comment by gulsensabak** [comment]
Issue related to database (https://github.com/bounswe/bounswe2024group10/issues/50) is edited

**Comment by Pqrq** [comment]
Issue related to mobile application (#53) is edited

**Comment by gulsensabak** [comment]
I think, we should determine more clear title since the person who read that issue cannot understand the topic directly. We have talked about that issue in our meeting so we know what the "edit issue" means, but not the other people know including our teachers. What do you think aout that title: "Filling the description and tasks part for the first issues related our subgroups"
@melihakpinar @karatashsyn @bartukonca @Pqrq

**Comment by Pqrq** [comment]
Your title idea seems to be too long for an issue title. I think it should be shorter, clear and concise

What about something like "Editing the Issues for Web/Mobile, Backend and Database" ?

**Comment by gulsensabak** [comment]
I think your title idea is more suitable than my idea. You can change it like that and close the issue if there is no more suggestion. Thank you @Pqrq.

**Comment by NazlicanAka** [comment]
I have changed the title, and it seems that every grup edit their issues and created their labels. So, I am closing this issue.
